"""empty message

Revision ID: 2a2ed3792d68
Revises: 58e16a90bb63
Create Date: 2020-09-02 17:25:18.613661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2ed3792d68'
down_revision = '58e16a90bb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funny', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('publication', sa.Column('phno', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'phno')
    op.drop_column('funny', 'is_active')
    # ### end Alembic commands ###
