"""empty message

Revision ID: 58e16a90bb63
Revises: 
Create Date: 2020-09-02 12:02:37.520439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e16a90bb63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phno', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('publication', sa.Column('phno', sa.String(length=13), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'phno')
    op.drop_table('funny')
    # ### end Alembic commands ###
