"""empty message

Revision ID: 99dda84871eb
Revises: 2a2ed3792d68
Create Date: 2020-09-02 17:27:31.506411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dda84871eb'
down_revision = '2a2ed3792d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('phno', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'phno')
    # ### end Alembic commands ###
